<a href="https://colab.research.google.com/github/AhamedShimak/pytorch/blob/main/code_along.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Saving the colab project in Github 

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
!nvidia-smi

### Tensors

In [9]:
#scaler
scaler= torch.tensor(7)
print(scaler.ndim)
print(scaler.item())
print(scaler.shape)

0
7
torch.Size([])


In [13]:
#vector
vector=torch.tensor([3,3])
print(vector.ndim)
print(vector)
print(vector.shape)
vector[0]

1
tensor([3, 3])
torch.Size([2])


tensor(3)

In [24]:
#MATRIX

MATRIX=torch.tensor([[1,2],[2,3],[2,34]])
print(MATRIX.ndim)
print(MATRIX)
print(MATRIX.shape)
MATRIX[0]

2
tensor([[ 1,  2],
        [ 2,  3],
        [ 2, 34]])
torch.Size([3, 2])


tensor([1, 2])

In [22]:
#TENSOR

TENSOR=torch.tensor([[[1,2],[2,3],[2,34]],[[1,2],[2,3],[2,34]],[[1,2],[2,3],[2,34]]])
print(TENSOR.ndim)
print(TENSOR)
print(TENSOR.shape)
TENSOR[0]

3
tensor([[[ 1,  2],
         [ 2,  3],
         [ 2, 34]],

        [[ 1,  2],
         [ 2,  3],
         [ 2, 34]],

        [[ 1,  2],
         [ 2,  3],
         [ 2, 34]]])
torch.Size([3, 3, 2])


tensor([[ 1,  2],
        [ 2,  3],
        [ 2, 34]])

##RandoM TeNSoRs

In [ ]:
random_tensor=torch.rand(3,224,224)
print(random_tensor.ndim)
print(random_tensor)
print(random_tensor.shape)
random_tensor[0]

In [50]:
random_tensor2=torch.rand(224)
print(random_tensor2.ndim)
print(random_tensor2)
print(random_tensor2.shape)
random_tensor2[1]

1
tensor([0.9312, 0.6647, 0.1640, 0.8614, 0.2772, 0.7753, 0.3532, 0.0428, 0.3055,
        0.5388, 0.4610, 0.6770, 0.1033, 0.5129, 0.1569, 0.9928, 0.8708, 0.0408,
        0.4829, 0.3748, 0.5092, 0.5968, 0.2821, 0.3039, 0.7375, 0.3771, 0.9980,
        0.0509, 0.9900, 0.7471, 0.9971, 0.4561, 0.3662, 0.3148, 0.4219, 0.9896,
        0.1559, 0.8913, 0.1226, 0.6133, 0.1489, 0.1731, 0.3796, 0.7418, 0.7711,
        0.9051, 0.9246, 0.2122, 0.8528, 0.8529, 0.0639, 0.0129, 0.8861, 0.6687,
        0.1035, 0.1464, 0.5326, 0.1878, 0.2157, 0.0089, 0.0993, 0.2444, 0.0268,
        0.4621, 0.7202, 0.5004, 0.3826, 0.6402, 0.7420, 0.7588, 0.9527, 0.1988,
        0.4870, 0.1717, 0.6855, 0.4054, 0.2747, 0.4384, 0.8938, 0.9021, 0.6146,
        0.0260, 0.5104, 0.6837, 0.7931, 0.5265, 0.0044, 0.3319, 0.9191, 0.0541,
        0.0056, 0.8226, 0.1014, 0.6681, 0.7361, 0.8039, 0.9130, 0.2373, 0.4295,
        0.0523, 0.4574, 0.3277, 0.4174, 0.8961, 0.6185, 0.7757, 0.4571, 0.9873,
        0.7651, 0.5009, 0.5306, 0.8692

tensor(0.6647)

##ZEROS AND ONE

In [58]:
zeros=torch.zeros(2,3,4)
print(zeros.ndim)
print(zeros)
print(zeros.shape)
zeros[1]

3
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [63]:
ones=torch.ones(2,3,4)
print(ones.ndim)
print(ones)
print(ones.shape)
ones[1]

3
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([2, 3, 4])


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##RANGE OF TENSOR

In [67]:
torch.arange(start=0,end=100,step=40)

tensor([ 0, 40, 80])

In [68]:
torch.zeros_like(torch.arange(start=0,end=100,step=40))

tensor([0, 0, 0])

In [69]:
torch.arange(start=0,end=100,step=40)*0

tensor([0, 0, 0])

##DATA TYPE TENSOR

In [79]:
float_32_tens=torch.tensor([1.0,2.2],dtype=None)
float_32_tens

tensor([1.0000, 2.2000])

In [82]:
float_32_tens=torch.tensor([1.0,2.2] ,device=None, requires_grad=False)
float_32_tens

tensor([1.0000, 2.2000])

In [87]:
float_16=float_32_tens.type(torch.float64)
float_16

tensor([1.0000, 2.2000], dtype=torch.float64)

##GET INFO FROM TENSOR

In [91]:
print(MATRIX.shape)
print(MATRIX.dtype)
print(MATRIX.device)

torch.Size([3, 2])
torch.int64
cpu


##MY FUNCTION

In [107]:
def details(tensor):
  print("")
  print("Shape: ",tensor.shape)
  print("Dimentions: ",tensor.ndim)
  print("###########")
  print(tensor)
  print("###########")
  print("Tensor Data type: ",tensor.dtype)
  print("Device: ",tensor.device)
  print("")

##MANIPULATING / TENSOR OPERATIONS

In [103]:
t=torch.rand(2,3,4)
details(t)

Shape:  torch.Size([2, 3, 4])
Dimentions:  3
###########
tensor([[[0.3796, 0.8016, 0.5551, 0.5097],
         [0.8915, 0.2737, 0.7504, 0.1455],
         [0.2125, 0.4841, 0.3566, 0.3411]],

        [[0.0693, 0.2499, 0.8695, 0.9120],
         [0.3530, 0.0802, 0.5449, 0.4456],
         [0.4018, 0.3155, 0.4969, 0.3121]]])
###########
Tensor Data type:  torch.float32
Device:  cpu


In [101]:
t_1=torch.rand(2,3,4)
details(t_1)

Shape:  torch.Size([2, 3, 4])
Dimentions:  3
###########
tensor([[[0.7346, 0.2099, 0.5405, 0.2353],
         [0.0416, 0.5036, 0.3686, 0.0081],
         [0.6518, 0.0788, 0.8721, 0.6708]],

        [[0.8009, 0.6394, 0.1152, 0.8369],
         [0.5428, 0.3872, 0.5169, 0.6749],
         [0.3249, 0.0429, 0.6637, 0.6218]]])
###########
Tensor Data type:  torch.float32
Device:  cpu


In [ ]:
details(t+1)
details(t+t_1)
details(t*4)
details(t*0)