<a href="https://colab.research.google.com/github/AhamedShimak/pytorch/blob/main/code_along.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Saving the colab project in Github 

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
!nvidia-smi

### Tensors

In [9]:
#scaler
scaler= torch.tensor(7)
print(scaler.ndim)
print(scaler.item())
print(scaler.shape)

0
7
torch.Size([])


In [13]:
#vector
vector=torch.tensor([3,3])
print(vector.ndim)
print(vector)
print(vector.shape)
vector[0]

1
tensor([3, 3])
torch.Size([2])


tensor(3)

In [24]:
#MATRIX

MATRIX=torch.tensor([[1,2],[2,3],[2,34]])
print(MATRIX.ndim)
print(MATRIX)
print(MATRIX.shape)
MATRIX[0]

2
tensor([[ 1,  2],
        [ 2,  3],
        [ 2, 34]])
torch.Size([3, 2])


tensor([1, 2])

In [22]:
#TENSOR

TENSOR=torch.tensor([[[1,2],[2,3],[2,34]],[[1,2],[2,3],[2,34]],[[1,2],[2,3],[2,34]]])
print(TENSOR.ndim)
print(TENSOR)
print(TENSOR.shape)
TENSOR[0]

3
tensor([[[ 1,  2],
         [ 2,  3],
         [ 2, 34]],

        [[ 1,  2],
         [ 2,  3],
         [ 2, 34]],

        [[ 1,  2],
         [ 2,  3],
         [ 2, 34]]])
torch.Size([3, 3, 2])


tensor([[ 1,  2],
        [ 2,  3],
        [ 2, 34]])

##RandoM TeNSoRs

In [ ]:
random_tensor=torch.rand(3,224,224)
print(random_tensor.ndim)
print(random_tensor)
print(random_tensor.shape)
random_tensor[0]

In [50]:
random_tensor2=torch.rand(224)
print(random_tensor2.ndim)
print(random_tensor2)
print(random_tensor2.shape)
random_tensor2[1]

1
tensor([0.9312, 0.6647, 0.1640, 0.8614, 0.2772, 0.7753, 0.3532, 0.0428, 0.3055,
        0.5388, 0.4610, 0.6770, 0.1033, 0.5129, 0.1569, 0.9928, 0.8708, 0.0408,
        0.4829, 0.3748, 0.5092, 0.5968, 0.2821, 0.3039, 0.7375, 0.3771, 0.9980,
        0.0509, 0.9900, 0.7471, 0.9971, 0.4561, 0.3662, 0.3148, 0.4219, 0.9896,
        0.1559, 0.8913, 0.1226, 0.6133, 0.1489, 0.1731, 0.3796, 0.7418, 0.7711,
        0.9051, 0.9246, 0.2122, 0.8528, 0.8529, 0.0639, 0.0129, 0.8861, 0.6687,
        0.1035, 0.1464, 0.5326, 0.1878, 0.2157, 0.0089, 0.0993, 0.2444, 0.0268,
        0.4621, 0.7202, 0.5004, 0.3826, 0.6402, 0.7420, 0.7588, 0.9527, 0.1988,
        0.4870, 0.1717, 0.6855, 0.4054, 0.2747, 0.4384, 0.8938, 0.9021, 0.6146,
        0.0260, 0.5104, 0.6837, 0.7931, 0.5265, 0.0044, 0.3319, 0.9191, 0.0541,
        0.0056, 0.8226, 0.1014, 0.6681, 0.7361, 0.8039, 0.9130, 0.2373, 0.4295,
        0.0523, 0.4574, 0.3277, 0.4174, 0.8961, 0.6185, 0.7757, 0.4571, 0.9873,
        0.7651, 0.5009, 0.5306, 0.8692

tensor(0.6647)

##ZEROS AND ONE

In [58]:
zeros=torch.zeros(2,3,4)
print(zeros.ndim)
print(zeros)
print(zeros.shape)
zeros[1]

3
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [63]:
ones=torch.ones(2,3,4)
print(ones.ndim)
print(ones)
print(ones.shape)
ones[1]

3
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([2, 3, 4])


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##RANGE OF TENSOR

In [67]:
torch.arange(start=0,end=100,step=40)

tensor([ 0, 40, 80])

In [68]:
torch.zeros_like(torch.arange(start=0,end=100,step=40))

tensor([0, 0, 0])

In [69]:
torch.arange(start=0,end=100,step=40)*0

tensor([0, 0, 0])

##DATA TYPE TENSOR

In [79]:
float_32_tens=torch.tensor([1.0,2.2],dtype=None)
float_32_tens

tensor([1.0000, 2.2000])

In [82]:
float_32_tens=torch.tensor([1.0,2.2] ,device=None, requires_grad=False)
float_32_tens

tensor([1.0000, 2.2000])

In [87]:
float_16=float_32_tens.type(torch.float64)
float_16

tensor([1.0000, 2.2000], dtype=torch.float64)

##GET INFO FROM TENSOR

In [91]:
print(MATRIX.shape)
print(MATRIX.dtype)
print(MATRIX.device)

torch.Size([3, 2])
torch.int64
cpu


##MY FUNCTION

In [2]:
import torch
def details(tensor):
  print("")
  print("Shape: ",tensor.shape)
  print("Dimentions: ",tensor.ndim)
  print("###########")
  print(tensor)
  print("###########")
  print("Tensor Data type: ",tensor.dtype)
  print("Device: ",tensor.device)
  print("")

##MANIPULATING / TENSOR OPERATIONS

In [3]:
t=torch.rand(2,3,4)
details(t)
t_1=torch.rand(2,3,4)
details(t_1)


Shape:  torch.Size([2, 3, 4])
Dimentions:  3
###########
tensor([[[0.6768, 0.2560, 0.6969, 0.1026],
         [0.7872, 0.3013, 0.8168, 0.0735],
         [0.2441, 0.7941, 0.6309, 0.3067]],

        [[0.3284, 0.0077, 0.1634, 0.5597],
         [0.1879, 0.6758, 0.0633, 0.0298],
         [0.7092, 0.8760, 0.9342, 0.6488]]])
###########
Tensor Data type:  torch.float32
Device:  cpu


Shape:  torch.Size([2, 3, 4])
Dimentions:  3
###########
tensor([[[0.2803, 0.4340, 0.7691, 0.3508],
         [0.1614, 0.7867, 0.7086, 0.5649],
         [0.5690, 0.2267, 0.8365, 0.4286]],

        [[0.8849, 0.0916, 0.3303, 0.6954],
         [0.7975, 0.0286, 0.2194, 0.0805],
         [0.9446, 0.3586, 0.3263, 0.7336]]])
###########
Tensor Data type:  torch.float32
Device:  cpu



In [ ]:
%%time
details(t+1)
details(t+t_1)
details(t*4)
details(t*0)
details(t*t_1) #element_wise multiplication
details(torch.matmul(torch.rand(2,3),torch.rand(3,2))) #dot product
details(torch.rand(200,200,300) @ torch.rand(200,300,200)) #DOT
#matmal and @ and mm are same



Transpose

In [13]:
t=torch.rand(2,3)
details(t)
details(t.T) #transpose
details(t@t.T)
details(torch.mm(t.T,t))


Shape:  torch.Size([2, 3])
Dimentions:  2
###########
tensor([[5.1537e-01, 6.5937e-01, 1.1006e-01],
        [3.4970e-04, 5.1001e-01, 4.5537e-01]])
###########
Tensor Data type:  torch.float32
Device:  cpu


Shape:  torch.Size([3, 2])
Dimentions:  2
###########
tensor([[5.1537e-01, 3.4970e-04],
        [6.5937e-01, 5.1001e-01],
        [1.1006e-01, 4.5537e-01]])
###########
Tensor Data type:  torch.float32
Device:  cpu


Shape:  torch.Size([2, 2])
Dimentions:  2
###########
tensor([[0.7125, 0.3866],
        [0.3866, 0.4675]])
###########
Tensor Data type:  torch.float32
Device:  cpu


Shape:  torch.Size([3, 3])
Dimentions:  2
###########
tensor([[0.2656, 0.3400, 0.0569],
        [0.3400, 0.6949, 0.3048],
        [0.0569, 0.3048, 0.2195]])
###########
Tensor Data type:  torch.float32
Device:  cpu



##TENSOR AGGREGATION

getting info

In [25]:
x=torch.arange(start=2,end=200,step=3)
details(x)
torch.max(x),torch.min(x), torch.mean(x.type(torch.float32)) #######



Shape:  torch.Size([66])
Dimentions:  1
###########
tensor([  2,   5,   8,  11,  14,  17,  20,  23,  26,  29,  32,  35,  38,  41,
         44,  47,  50,  53,  56,  59,  62,  65,  68,  71,  74,  77,  80,  83,
         86,  89,  92,  95,  98, 101, 104, 107, 110, 113, 116, 119, 122, 125,
        128, 131, 134, 137, 140, 143, 146, 149, 152, 155, 158, 161, 164, 167,
        170, 173, 176, 179, 182, 185, 188, 191, 194, 197])
###########
Tensor Data type:  torch.int64
Device:  cpu



(tensor(197), tensor(2), tensor(99.5000))

In [38]:
t_rand=torch.rand(100,100)
details(t_rand)
torch.max(t_rand),torch.min(t_rand), torch.mean(t_rand.type(torch.float32)),torch.argmax(t_rand), torch.argmin(t_rand)


Shape:  torch.Size([100, 100])
Dimentions:  2
###########
tensor([[0.7171, 0.8651, 0.2796,  ..., 0.8743, 0.8152, 0.8554],
        [0.1335, 0.8017, 0.2819,  ..., 0.2916, 0.8654, 0.5713],
        [0.3347, 0.9785, 0.4370,  ..., 0.7535, 0.2144, 0.8242],
        ...,
        [0.6385, 0.0845, 0.7517,  ..., 0.6007, 0.1187, 0.7000],
        [0.7854, 0.7544, 0.5294,  ..., 0.5348, 0.9578, 0.7195],
        [0.8131, 0.4626, 0.6244,  ..., 0.7461, 0.3100, 0.0066]])
###########
Tensor Data type:  torch.float32
Device:  cpu



(tensor(0.9999), tensor(0.0001), tensor(0.5050), tensor(1897), tensor(2596))

##RESHAPING, STACKING, SQUEEZING AND UNSQUEEZING tensors


| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`torch.Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. | 
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. | 
