<a href="https://colab.research.google.com/github/AhamedShimak/pytorch/blob/main/code_along.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Initiating Pytorch

### Imports

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


###MY DETAILS FUNCTION

In [ ]:
import torch
def details(tensor):
  print("")
  print("Shape: ",tensor.shape)
  print("Dimentions: ",tensor.ndim)
  print("###########")
  print(tensor)
  print("###########")
  print("Tensor Data type: ",tensor.dtype)
  print("Device: ",tensor.device)
  print("")

###GPU

In [20]:
!nvidia-smi
print(torch.cuda.is_available())
#setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
print(device)

Tue Apr 18 16:11:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P0    29W /  70W |    601MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

##PUTTING TENSORS/MODELS IN GPU

In [16]:
%%time
tensor= torch.rand((3,45,56),device=device)
tensor_on_gpu=tensor.to("cuda")
tensor_on_cpu=tensor.to("cpu")
details(tensor)
details(tensor_on_cpu)



Shape:  torch.Size([3, 45, 56])
Dimentions:  3
###########
tensor([[[0.2966, 0.7621, 0.6128,  ..., 0.8793, 0.7682, 0.6692],
         [0.5781, 0.9374, 0.6518,  ..., 0.5449, 0.4440, 0.6614],
         [0.5469, 0.5696, 0.8549,  ..., 0.6205, 0.9891, 0.3086],
         ...,
         [0.5663, 0.3017, 0.8185,  ..., 0.5208, 0.0920, 0.0931],
         [0.9668, 0.1505, 0.5371,  ..., 0.9444, 0.5445, 0.8324],
         [0.1798, 0.9539, 0.3874,  ..., 0.0326, 0.9004, 0.4010]],

        [[0.4648, 0.5016, 0.4053,  ..., 0.6815, 0.9206, 0.2063],
         [0.9594, 0.7513, 0.4217,  ..., 0.7443, 0.5863, 0.2113],
         [0.9358, 0.2548, 0.5510,  ..., 0.8940, 0.0192, 0.1620],
         ...,
         [0.7368, 0.6729, 0.6481,  ..., 0.0536, 0.0876, 0.9366],
         [0.5078, 0.2941, 0.2343,  ..., 0.3599, 0.2404, 0.1551],
         [0.6787, 0.6482, 0.1679,  ..., 0.6336, 0.7432, 0.2441]],

        [[0.5674, 0.8350, 0.0385,  ..., 0.9166, 0.6016, 0.6989],
         [0.6442, 0.1921, 0.8416,  ..., 0.6479, 0.2787, 0.4764]

### Tensors

In [3]:
#scaler
scaler= torch.tensor(7)
print(scaler.ndim)
print(scaler.item())
print(scaler.shape)

0
7
torch.Size([])


In [4]:
#vector
vector=torch.tensor([3,3])
print(vector.ndim)
print(vector)
print(vector.shape)
vector[0]

1
tensor([3, 3])
torch.Size([2])


tensor(3)

In [5]:
#MATRIX

MATRIX=torch.tensor([[1,2],[2,3],[2,34]])
print(MATRIX.ndim)
print(MATRIX)
print(MATRIX.shape)
MATRIX[0]

2
tensor([[ 1,  2],
        [ 2,  3],
        [ 2, 34]])
torch.Size([3, 2])


tensor([1, 2])

In [6]:
#TENSOR

TENSOR=torch.tensor([[[1,2],[2,3],[2,34]],[[1,2],[2,3],[2,34]],[[1,2],[2,3],[2,34]]])
print(TENSOR.ndim)
print(TENSOR)
print(TENSOR.shape)
TENSOR[0]

3
tensor([[[ 1,  2],
         [ 2,  3],
         [ 2, 34]],

        [[ 1,  2],
         [ 2,  3],
         [ 2, 34]],

        [[ 1,  2],
         [ 2,  3],
         [ 2, 34]]])
torch.Size([3, 3, 2])


tensor([[ 1,  2],
        [ 2,  3],
        [ 2, 34]])

##RandoM TeNSoRs

In [ ]:
random_tensor=torch.rand(3,224,224)
print(random_tensor.ndim)
print(random_tensor)
print(random_tensor.shape)
random_tensor[0]

In [ ]:
random_tensor2=torch.rand(224)
print(random_tensor2.ndim)
print(random_tensor2)
print(random_tensor2.shape)
random_tensor2[1]

1
tensor([0.9312, 0.6647, 0.1640, 0.8614, 0.2772, 0.7753, 0.3532, 0.0428, 0.3055,
        0.5388, 0.4610, 0.6770, 0.1033, 0.5129, 0.1569, 0.9928, 0.8708, 0.0408,
        0.4829, 0.3748, 0.5092, 0.5968, 0.2821, 0.3039, 0.7375, 0.3771, 0.9980,
        0.0509, 0.9900, 0.7471, 0.9971, 0.4561, 0.3662, 0.3148, 0.4219, 0.9896,
        0.1559, 0.8913, 0.1226, 0.6133, 0.1489, 0.1731, 0.3796, 0.7418, 0.7711,
        0.9051, 0.9246, 0.2122, 0.8528, 0.8529, 0.0639, 0.0129, 0.8861, 0.6687,
        0.1035, 0.1464, 0.5326, 0.1878, 0.2157, 0.0089, 0.0993, 0.2444, 0.0268,
        0.4621, 0.7202, 0.5004, 0.3826, 0.6402, 0.7420, 0.7588, 0.9527, 0.1988,
        0.4870, 0.1717, 0.6855, 0.4054, 0.2747, 0.4384, 0.8938, 0.9021, 0.6146,
        0.0260, 0.5104, 0.6837, 0.7931, 0.5265, 0.0044, 0.3319, 0.9191, 0.0541,
        0.0056, 0.8226, 0.1014, 0.6681, 0.7361, 0.8039, 0.9130, 0.2373, 0.4295,
        0.0523, 0.4574, 0.3277, 0.4174, 0.8961, 0.6185, 0.7757, 0.4571, 0.9873,
        0.7651, 0.5009, 0.5306, 0.8692

tensor(0.6647)

##ZEROS AND ONE

In [ ]:
zeros=torch.zeros(2,3,4)
print(zeros.ndim)
print(zeros)
print(zeros.shape)
zeros[1]

3
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(2,3,4)
print(ones.ndim)
print(ones)
print(ones.shape)
ones[1]

3
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([2, 3, 4])


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##RANGE OF TENSOR

In [ ]:
torch.arange(start=0,end=100,step=40)

tensor([ 0, 40, 80])

In [ ]:
torch.zeros_like(torch.arange(start=0,end=100,step=40))

tensor([0, 0, 0])

In [ ]:
torch.arange(start=0,end=100,step=40)*0

tensor([0, 0, 0])

##DATA TYPE TENSOR

In [ ]:
float_32_tens=torch.tensor([1.0,2.2],dtype=None)
float_32_tens

tensor([1.0000, 2.2000])

In [ ]:
float_32_tens=torch.tensor([1.0,2.2] ,device=None, requires_grad=False)
float_32_tens

tensor([1.0000, 2.2000])

In [ ]:
float_16=float_32_tens.type(torch.float64)
float_16

tensor([1.0000, 2.2000], dtype=torch.float64)

##GET INFO FROM TENSOR

In [ ]:
print(MATRIX.shape)
print(MATRIX.dtype)
print(MATRIX.device)

torch.Size([3, 2])
torch.int64
cpu


##MANIPULATING / TENSOR OPERATIONS

In [ ]:
t=torch.rand(2,3,4)
details(t)
t_1=torch.rand(2,3,4)
details(t_1)


Shape:  torch.Size([2, 3, 4])
Dimentions:  3
###########
tensor([[[0.6768, 0.2560, 0.6969, 0.1026],
         [0.7872, 0.3013, 0.8168, 0.0735],
         [0.2441, 0.7941, 0.6309, 0.3067]],

        [[0.3284, 0.0077, 0.1634, 0.5597],
         [0.1879, 0.6758, 0.0633, 0.0298],
         [0.7092, 0.8760, 0.9342, 0.6488]]])
###########
Tensor Data type:  torch.float32
Device:  cpu


Shape:  torch.Size([2, 3, 4])
Dimentions:  3
###########
tensor([[[0.2803, 0.4340, 0.7691, 0.3508],
         [0.1614, 0.7867, 0.7086, 0.5649],
         [0.5690, 0.2267, 0.8365, 0.4286]],

        [[0.8849, 0.0916, 0.3303, 0.6954],
         [0.7975, 0.0286, 0.2194, 0.0805],
         [0.9446, 0.3586, 0.3263, 0.7336]]])
###########
Tensor Data type:  torch.float32
Device:  cpu



In [ ]:
%%time
details(t+1)
details(t+t_1)
details(t*4)
details(t*0)
details(t*t_1) #element_wise multiplication
details(torch.matmul(torch.rand(2,3),torch.rand(3,2))) #dot product
details(torch.rand(200,200,300) @ torch.rand(200,300,200)) #DOT
#matmal and @ and mm are same



Transpose

In [ ]:
t=torch.rand(2,3)
details(t)
details(t.T) #transpose
details(t@t.T)
details(torch.mm(t.T,t))


Shape:  torch.Size([2, 3])
Dimentions:  2
###########
tensor([[5.1537e-01, 6.5937e-01, 1.1006e-01],
        [3.4970e-04, 5.1001e-01, 4.5537e-01]])
###########
Tensor Data type:  torch.float32
Device:  cpu


Shape:  torch.Size([3, 2])
Dimentions:  2
###########
tensor([[5.1537e-01, 3.4970e-04],
        [6.5937e-01, 5.1001e-01],
        [1.1006e-01, 4.5537e-01]])
###########
Tensor Data type:  torch.float32
Device:  cpu


Shape:  torch.Size([2, 2])
Dimentions:  2
###########
tensor([[0.7125, 0.3866],
        [0.3866, 0.4675]])
###########
Tensor Data type:  torch.float32
Device:  cpu


Shape:  torch.Size([3, 3])
Dimentions:  2
###########
tensor([[0.2656, 0.3400, 0.0569],
        [0.3400, 0.6949, 0.3048],
        [0.0569, 0.3048, 0.2195]])
###########
Tensor Data type:  torch.float32
Device:  cpu



##TENSOR AGGREGATION

getting info

In [12]:
x=torch.arange(start=2,end=200,step=3)
details(x)
torch.max(x),torch.min(x), torch.mean(x.type(torch.float32)) #######



Shape:  torch.Size([66])
Dimentions:  1
###########
tensor([  2,   5,   8,  11,  14,  17,  20,  23,  26,  29,  32,  35,  38,  41,
         44,  47,  50,  53,  56,  59,  62,  65,  68,  71,  74,  77,  80,  83,
         86,  89,  92,  95,  98, 101, 104, 107, 110, 113, 116, 119, 122, 125,
        128, 131, 134, 137, 140, 143, 146, 149, 152, 155, 158, 161, 164, 167,
        170, 173, 176, 179, 182, 185, 188, 191, 194, 197])
###########
Tensor Data type:  torch.int64
Device:  cpu



(tensor(197), tensor(2), tensor(99.5000))

In [13]:
t_rand=torch.rand(100,100)
details(t_rand)
torch.max(t_rand),torch.min(t_rand), torch.mean(t_rand.type(torch.float32)),torch.argmax(t_rand), torch.argmin(t_rand)


Shape:  torch.Size([100, 100])
Dimentions:  2
###########
tensor([[0.7949, 0.7668, 0.3458,  ..., 0.4033, 0.1710, 0.4871],
        [0.1711, 0.6599, 0.6598,  ..., 0.2338, 0.7982, 0.6637],
        [0.4942, 0.2875, 0.0505,  ..., 0.4009, 0.7349, 0.3366],
        ...,
        [0.0272, 0.6804, 0.4561,  ..., 0.0273, 0.8513, 0.8240],
        [0.7731, 0.9356, 0.1988,  ..., 0.3608, 0.3274, 0.7279],
        [0.8973, 0.1904, 0.0917,  ..., 0.8731, 0.4893, 0.5331]])
###########
Tensor Data type:  torch.float32
Device:  cpu



(tensor(1.0000), tensor(0.0001), tensor(0.5074), tensor(2710), tensor(449))

##RESHAPING, STACKING, SQUEEZING AND UNSQUEEZING tensors


| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`torch.Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. | 
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. | 


In [22]:
t=torch.rand(2,2,4)
details(t)


Shape:  torch.Size([2, 2, 4])
Dimentions:  3
###########
tensor([[[0.8655, 0.9365, 0.7936, 0.5628],
         [0.3409, 0.3457, 0.7268, 0.5925]],

        [[0.0592, 0.3161, 0.6600, 0.6613],
         [0.3375, 0.0897, 0.2603, 0.8633]]])
###########
Tensor Data type:  torch.float32
Device:  cpu



In [32]:
t_reshaped=t.reshape(4,2,2)
details(t_reshaped)


Shape:  torch.Size([4, 2, 2])
Dimentions:  3
###########
tensor([[[0.8655, 0.9365],
         [0.7936, 0.5628]],

        [[0.3409, 0.3457],
         [0.7268, 0.5925]],

        [[0.0592, 0.3161],
         [0.6600, 0.6613]],

        [[0.3375, 0.0897],
         [0.2603, 0.8633]]])
###########
Tensor Data type:  torch.float32
Device:  cpu



In [31]:
t_reshaped=t.reshape(2,8)
details(t_reshaped)


Shape:  torch.Size([2, 8])
Dimentions:  2
###########
tensor([[0.8655, 0.9365, 0.7936, 0.5628, 0.3409, 0.3457, 0.7268, 0.5925],
        [0.0592, 0.3161, 0.6600, 0.6613, 0.3375, 0.0897, 0.2603, 0.8633]])
###########
Tensor Data type:  torch.float32
Device:  cpu



In [35]:
t_view=t.view(8,2)
details(t_view)


Shape:  torch.Size([8, 2])
Dimentions:  2
###########
tensor([[0.8655, 0.9365],
        [0.7936, 0.5628],
        [0.3409, 0.3457],
        [0.7268, 0.5925],
        [0.0592, 0.3161],
        [0.6600, 0.6613],
        [0.3375, 0.0897],
        [0.2603, 0.8633]])
###########
Tensor Data type:  torch.float32
Device:  cpu



In [56]:
#stack
details(t)
details(torch.stack([t,t,t]))
details(torch.stack([t,t,t],dim=-3))


Shape:  torch.Size([2, 2, 4])
Dimentions:  3
###########
tensor([[[8.0000, 0.9365, 0.7936, 0.5628],
         [0.3409, 0.3457, 0.7268, 0.5925]],

        [[0.0592, 0.3161, 0.6600, 0.6613],
         [0.3375, 0.0897, 0.2603, 0.8633]]])
###########
Tensor Data type:  torch.float32
Device:  cpu


Shape:  torch.Size([3, 2, 2, 4])
Dimentions:  4
###########
tensor([[[[8.0000, 0.9365, 0.7936, 0.5628],
          [0.3409, 0.3457, 0.7268, 0.5925]],

         [[0.0592, 0.3161, 0.6600, 0.6613],
          [0.3375, 0.0897, 0.2603, 0.8633]]],


        [[[8.0000, 0.9365, 0.7936, 0.5628],
          [0.3409, 0.3457, 0.7268, 0.5925]],

         [[0.0592, 0.3161, 0.6600, 0.6613],
          [0.3375, 0.0897, 0.2603, 0.8633]]],


        [[[8.0000, 0.9365, 0.7936, 0.5628],
          [0.3409, 0.3457, 0.7268, 0.5925]],

         [[0.0592, 0.3161, 0.6600, 0.6613],
          [0.3375, 0.0897, 0.2603, 0.8633]]]])
###########
Tensor Data type:  torch.float32
Device:  cpu


Shape:  torch.Size([2, 3, 2, 4])
Dimentio

In [63]:
t_reshped=t.reshape(2,1,2,1,2,2)
t_squeezed=t_reshped.squeeze()
details(t_reshped)
details(t_squeezed)


Shape:  torch.Size([2, 1, 2, 1, 2, 2])
Dimentions:  6
###########
tensor([[[[[[8.0000, 0.9365],
            [0.7936, 0.5628]]],


          [[[0.3409, 0.3457],
            [0.7268, 0.5925]]]]],




        [[[[[0.0592, 0.3161],
            [0.6600, 0.6613]]],


          [[[0.3375, 0.0897],
            [0.2603, 0.8633]]]]]])
###########
Tensor Data type:  torch.float32
Device:  cpu


Shape:  torch.Size([2, 2, 2, 2])
Dimentions:  4
###########
tensor([[[[8.0000, 0.9365],
          [0.7936, 0.5628]],

         [[0.3409, 0.3457],
          [0.7268, 0.5925]]],


        [[[0.0592, 0.3161],
          [0.6600, 0.6613]],

         [[0.3375, 0.0897],
          [0.2603, 0.8633]]]])
###########
Tensor Data type:  torch.float32
Device:  cpu



In [77]:
details(t_squeezed.unsqueeze(dim=-4))


Shape:  torch.Size([2, 1, 2, 2, 2])
Dimentions:  5
###########
tensor([[[[[8.0000, 0.9365],
           [0.7936, 0.5628]],

          [[0.3409, 0.3457],
           [0.7268, 0.5925]]]],



        [[[[0.0592, 0.3161],
           [0.6600, 0.6613]],

          [[0.3375, 0.0897],
           [0.2603, 0.8633]]]]])
###########
Tensor Data type:  torch.float32
Device:  cpu



In [90]:
#permute
img=torch.rand(224,224,3)
details(img.permute(2,1,0))
details(t.permute(1,2,0))


Shape:  torch.Size([3, 224, 224])
Dimentions:  3
###########
tensor([[[0.4395, 0.3973, 0.0568,  ..., 0.3007, 0.6045, 0.8145],
         [0.0855, 0.9508, 0.9973,  ..., 0.0132, 0.0260, 0.6812],
         [0.2670, 0.5845, 0.0223,  ..., 0.7772, 0.9917, 0.4384],
         ...,
         [0.7255, 0.3573, 0.2220,  ..., 0.4101, 0.5419, 0.3851],
         [0.4368, 0.3569, 0.0333,  ..., 0.0692, 0.7097, 0.2819],
         [0.4145, 0.8259, 0.6089,  ..., 0.5559, 0.6213, 0.5009]],

        [[0.9838, 0.6075, 0.7293,  ..., 0.5434, 0.0391, 0.6505],
         [0.0945, 0.5657, 0.0382,  ..., 0.5770, 0.6264, 0.2540],
         [0.8784, 0.6940, 0.4747,  ..., 0.4323, 0.8740, 0.0854],
         ...,
         [0.7973, 0.9116, 0.9559,  ..., 0.3950, 0.0063, 0.4336],
         [0.0233, 0.4115, 0.0715,  ..., 0.8164, 0.3637, 0.6017],
         [0.3733, 0.3351, 0.8613,  ..., 0.2718, 0.8843, 0.3207]],

        [[0.1054, 0.7345, 0.3495,  ..., 0.8391, 0.2559, 0.0146],
         [0.9504, 0.0187, 0.3794,  ..., 0.7556, 0.8353, 0.041

##INDEXING

In [ ]:
t_ind=torch.rand(3,4,3)
details(t_ind)

In [93]:
details(t_ind)


Shape:  torch.Size([3, 4, 3])
Dimentions:  3
###########
tensor([[[0.2129, 0.3892, 0.6646],
         [0.2391, 0.6666, 0.1325],
         [0.9155, 0.0415, 0.2001],
         [0.8411, 0.3987, 0.9757]],

        [[0.2928, 0.1222, 0.8182],
         [0.3344, 0.1611, 0.0394],
         [0.7867, 0.7796, 0.8921],
         [0.0188, 0.5531, 0.4419]],

        [[0.3489, 0.5901, 0.0372],
         [0.2203, 0.9013, 0.4158],
         [0.1617, 0.0162, 0.3352],
         [0.1550, 0.4308, 0.9764]]])
###########
Tensor Data type:  torch.float32
Device:  cpu



In [ ]:
details(t_ind)
details(t_ind[:,1:3,1:2])
details(t_ind[:,1:3,1:2].permute(0,2,1))
details(t_ind[:,1:3,1:2].permute(0,2,1).squeeze())
details(t_ind[:,1:3,1:2].permute(0,2,1).squeeze().reshape(1,6))
details(t_ind[:,1:3,1:2].permute(0,2,1).squeeze().reshape(6,1))
details(t_ind[:,1:3,1:2].reshape(1,6))

##PyTorch VS NUMPY

np-> tensor

In [134]:
array=np.random.rand(3,4,3)
print(array)
t=torch.from_numpy(array).type(torch.float32)
details(t)

[[[0.44392417 0.7339921  0.21919048]
  [0.2626536  0.00202837 0.99550895]
  [0.96077567 0.84135652 0.20931668]
  [0.58293401 0.10080511 0.24246185]]

 [[0.07135503 0.65073989 0.18134559]
  [0.86642857 0.6573871  0.78562076]
  [0.08221964 0.99973807 0.75865347]
  [0.46839925 0.15092914 0.0262429 ]]

 [[0.62722405 0.35611227 0.48787509]
  [0.26008876 0.17423045 0.35106623]
  [0.34523731 0.72160035 0.62353597]
  [0.21995284 0.84599258 0.70187262]]]

Shape:  torch.Size([3, 4, 3])
Dimentions:  3
###########
tensor([[[0.4439, 0.7340, 0.2192],
         [0.2627, 0.0020, 0.9955],
         [0.9608, 0.8414, 0.2093],
         [0.5829, 0.1008, 0.2425]],

        [[0.0714, 0.6507, 0.1813],
         [0.8664, 0.6574, 0.7856],
         [0.0822, 0.9997, 0.7587],
         [0.4684, 0.1509, 0.0262]],

        [[0.6272, 0.3561, 0.4879],
         [0.2601, 0.1742, 0.3511],
         [0.3452, 0.7216, 0.6235],
         [0.2200, 0.8460, 0.7019]]])
###########
Tensor Data type:  torch.float32
Device:  cpu



Tensor -> numpy

In [138]:
t=torch.rand(2,4,3)
details(t)
np_array=t.numpy()
np_array


Shape:  torch.Size([2, 4, 3])
Dimentions:  3
###########
tensor([[[8.9218e-01, 6.8080e-04, 9.0857e-01],
         [2.1075e-01, 7.6300e-01, 5.1533e-01],
         [3.5308e-01, 5.9524e-01, 8.3252e-01],
         [4.5159e-01, 6.6190e-01, 8.4987e-01]],

        [[3.0849e-01, 6.4975e-01, 2.4885e-01],
         [4.3424e-01, 3.6387e-01, 1.0189e-01],
         [5.7828e-01, 5.2201e-02, 9.2800e-01],
         [5.4441e-01, 9.9055e-01, 9.7384e-01]]])
###########
Tensor Data type:  torch.float32
Device:  cpu



array([[[8.9218116e-01, 6.8080425e-04, 9.0857238e-01],
        [2.1075165e-01, 7.6300049e-01, 5.1533061e-01],
        [3.5308105e-01, 5.9524107e-01, 8.3252066e-01],
        [4.5159066e-01, 6.6189843e-01, 8.4987092e-01]],

       [[3.0849046e-01, 6.4975381e-01, 2.4885190e-01],
        [4.3424118e-01, 3.6386883e-01, 1.0188919e-01],
        [5.7827878e-01, 5.2201450e-02, 9.2800468e-01],
        [5.4440892e-01, 9.9055427e-01, 9.7384119e-01]]], dtype=float32)

## REPRODUCBILITY

In [141]:
##reduce the randomness in prtorch
#**random seed**

In [144]:
random_t_a=torch.rand(3,4)
random_t_b=torch.rand(3,4)

details(random_t_a)
details(random_t_b)

print(random_t_a==random_t_b)


Shape:  torch.Size([3, 4])
Dimentions:  2
###########
tensor([[0.1727, 0.5740, 0.9273, 0.8834],
        [0.4938, 0.6235, 0.8979, 0.5598],
        [0.0762, 0.0620, 0.3599, 0.4307]])
###########
Tensor Data type:  torch.float32
Device:  cpu


Shape:  torch.Size([3, 4])
Dimentions:  2
###########
tensor([[0.2149, 0.4344, 0.8640, 0.3132],
        [0.3627, 0.2292, 0.8177, 0.1448],
        [0.8224, 0.5635, 0.5652, 0.0036]])
###########
Tensor Data type:  torch.float32
Device:  cpu

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [147]:
torch.manual_seed(43)
RANDOM_t_a=torch.rand(3,4)

torch.manual_seed(43)
RANDOM_t_b=torch.rand(3,4)

details(RANDOM_t_a)
details(RANDOM_t_b)

print(RANDOM_t_a==RANDOM_t_b)


Shape:  torch.Size([3, 4])
Dimentions:  2
###########
tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
###########
Tensor Data type:  torch.float32
Device:  cpu


Shape:  torch.Size([3, 4])
Dimentions:  2
###########
tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
###########
Tensor Data type:  torch.float32
Device:  cpu

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
